fix: Using different selectors for debug runs (#246)
When debugging a test, I was getting an error in the neovim messages
stating that the output folder for the test was not found. Inspecting
the neotest-java logs, I found that the problem was actually junit
failing to launch completely due to not finding the desired test:
```
DEBUG | 2026-01-21T17:22:22Z+0100 | ...st-java.nvim/lua/neotest-java/core/spec_builder/init.lua:103 | junit debug command:
/usr/lib/jvm/java-21-openjdk-amd64/bin/java  [...] -jar [path to standalone jar] execute [...] 
--select-method='it.unive.lisa.program.cfg.fixpoints.OptimizedFixpointTest#testCyclicGraph()'

ERROR | 2026-01-21T17:22:28Z+0100 | ...s/neotest-java.nvim/lua/neotest-java/build_tool/init.lua:74 | stderr:  
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	[...]
Caused by: java.lang.ClassNotFoundException: 'it.unive.lisa.program.cfg.fixpoints.OptimizedFixpointTest
	[...]
```
With the red herring being the single quote at the beginning of the
class name. Note that, excluding the -agentlib and the -Xdebug
parameters, the command line was identical (classpath included) to the
one used for running the test normally, which succeeded.

Single quotes were added for #216, since the `$` used for inner classes
was being expanded to a variable by the shell spawned for running the
test. However, after some digging, I found out that the `plenary.Job`
instance does not spawn a native shell, but instead uses
`vim.loop.spawn`. This means that it does not perform either variable
expansion or single/double quotes removal, and thus the error above.

I added a switch on the generation of the test selector that adds the
quotes only in a non-dap execution, which fixes the problem.